### ISSUE TITLE
Function to annotate fusion calls from Arriba

### ISSUE THREAD

**Issue by skanwal** [d3b-center/annoFuse#1]
Hello,

Thanks for this useful resource.

I am trying to find ways to use annoFuse for our internal RNAseq samples.
We use [bcbio-RNAseq pipeline](https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#rna-seq) for the processing of samples in a **single sample** setting. Also, our focus is on the fusion calls from Arriba.

I was thinking of starting with `annotate_fusion_calls` function to annotate Arriba calls and then later apply prioritisation. However, I have few questions;

- Would it be reasonable to use annoFuse on a single sample fusion calls? Or the tool is more useful for cohort based analysis? From the annoFuse paper it seems you had tested the tool on a cohort of samples from OpenPBTA project.

- If yes - can you please clarify what is expected as input for `geneListReferenceDataTab` and `fusionReferenceDataTab` in the `annotate_fusion_calls` function? I could not figure this out from the description in the man page. Can you please share any examples?

This will be much appreciated.

----
Sehrish K

**Comment by kgaonkar6** [comment]
Hi Sehrish, 

We did develop annoFuse to be used at cohort level filtering and prioritization . But if you can give more information about how you would like to use annoFuse I can help :)

You should be able to run the first 3 steps https://github.com/d3b-center/annoFuse/wiki of standardization, QC filtering and expression based filtering for single sample. Here's an example for a single sample run:

```
#install annoFuse
devtools::install_github("d3b-center/annoFuse")
library("annoFuse")

# read in caller results
Arribainputfile<-read_tsv("~/XYZ/123.arriba.fusions.tsv")
```

We require input arriba calls to have a "Sample","Caller" and "annots" column in addition to the standard Arriba output. We recommend using FusionAnnotator https://github.com/FusionAnnotator/FusionAnnotator/tree/v0.2.0 which adds a column "annots" which we have found very useful to gather database level annotation for fusion QC filtering (using artifactFilter="GTEx_Recurrent|DGD_PARALOGS|Normal|BodyMap|ConjoinG" in fusion_filtering_QC function ) .
If you don't want to add FusionAnnotator annotation you can simply add a column "annots" assign it "NA" or your own custom annotation you would like to use as QC filtering.

```
# add columns 
Arribainputfile$Sample<-"sampleID"
Arribainputfile$Caller<-"Arriba"

Arribainputfile$annots<-"NA"

# standardization of Arriba calls
standardizedArriba<-fusion_standardization(fusion_calls = Arribainputfile,caller = "ARRIBA")

# QC filtering if not using FusionAnnotator annots column for filtering,  only filter using cutoff for junction and spanning read support and readthrough fusion.
fusionQCarriba<-fusion_filtering_QC(standardFusioncalls=standardizedArriba, readingFrameFilter="in-frame|frameshift|other",artifactFilter="none",junctionReadCountFilter=1,spanningFragCountFilter=10,readthroughFilter=TRUE)
```

The geneListReferenceDataTab and fusionReferenceDataTab are available with the package you can access them from the extdata folder as below:

```
geneListReferenceDataTab<-read.delim(system.file("extdata", "genelistreference.txt", package="annoFuse"),stringsAsFactors = FALSE)
fusionReferenceDataTab<-read.delim(system.file("extdata", "fusionreference.txt", package="annoFuse"),stringsAsFactors = FALSE)

# annotation of filtered fusion calls
filteredFusionAnnotated<-annotate_fusion_calls(standardFusioncalls= fusionQCarriba,geneListReferenceDataTab=geneListReferenceDataTab,fusionReferenceDataTab=fusionReferenceDataTab)

```


Also please update the package using devtools::install_github("d3b-center/annoFuse") I've made some edits to annotate_fusion_calls.

**Comment by skanwal** [comment]
Hello and thanks for the response @kgaonkar6.

For now, I am playing a bit with the tool to get a sense about the functionality and understand if it can be used to prioritise fusion calls from a single RNA sample.

I have a couple more questions:

- Wrt `fusion_filtering_QC` function, if we set `spanningFragCountFilter=10` - would it filter out fusions with spanningFragCountFilter<10? And same for `junctionReadCountFilter`?

- After applying the annotation on the filtered fusion calls, I am seeing few additional columns. Some of these are explained [here](https://github.com/d3b-center/annoFuse/wiki). 
I am wondering about few others such as `file.x.x`, `file.y.y` and `file`? 

---
Sehrish K

**Comment by kgaonkar6** [comment]
In order to standardize the fusion calls from different callers we had to rename a couple of columns from Arriba output, SpanningFragCount is equivalent to discordant_mates in Arriba and JunctionReadCount is equivalent to split reads in Arriba. (we add split_reads1 and split_reads2 because in Arriba split_read1 and split_reads2 provide information of reads anchoring in gene1 or gene2 , more information in Arriba docs.)


In fusion_filtering_QC 
`junctionReadCountFilter` is an integer threshold for JunctionReadCount . So any fusion with greater or equal to the given integer number of JunctionReadCount will be kept. Our default is atleast 1 JunctionReadCount.
`spanningFragCountFilter` is an integer threshold for SpanningFragCount - JunctionReadCount
We wanted to use spanningFragCountFilter to remove any fusion where there is a disproportionate larger number of SpanningFragCount reads to JunctionReadCount which can be removed as an artifact. So using our default any fusion where (SpanningFragCount - JunctionReadCount) <=10 is kept after running fusion_filtering_QC.

For the additional columns in annotation can you please update the package by running  devtools::install_github("d3b-center/annoFuse")  I've fixed the issue and now doesn't have the file.x.x and file.y.y which provided the information of which original files were used to get the gene and fusion reference list. 

Thanks!

**Comment by skanwal** [comment]
Hello,

As above you have suggested to look at https://github.com/FusionAnnotator/FusionAnnotator/tree/v0.2.0. The tool documentation is not clear around the input for `--genome_lib_dir` flag. 

Do you've a recommended input to use for hg38? There are quite a few files for v38 on https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/.  I was wondering if there is any specific one I should use to add `annots` as these are later picked-up/filtered by FusionAnnotator?

**Comment by kgaonkar6** [comment]
Hi,

We have used GRCh38_v27_CTAT_lib_Feb092018.plug-n-play.tar.gz for our analysis to annotate Arriba calls  seems to be the same file here https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/__genome_libs_StarFv1.3/

**Comment by kgaonkar6** [comment]
Hi @skanwal were you able to use the package to annotate your fusion calls?

**Comment by skanwal** [comment]
Hello,

Thanks for checking and yes, I was able to annotate the fusion calls.
I'll close this issue.

Cheers.

**Comment by serignebasse** [comment]
Y @kgaonkar6 ,I have problems for using annoFuse to annotate arriba and Star_fusion results. Can you help me. Y have this error:
Error in `dplyr::mutate()`:
ℹ In argument: `FusionName = paste0(gsub(",", "/", .data$`#gene1`), "--", gsub(",", "/", .data$gene2))`.
Caused by error in `` .data$`#gene1` ``:
! Column `#gene1` not found in `.data`.
