### ISSUE TITLE
add kinase domain retention info to putative oncogenic file

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#66]
add `kinaseGeneDomainRetained` and rename `GeneLoc` -> `kinaseDomainGeneLoc`

**Comment by kgaonkar6** [comment]
Since I'm adding the this as part of the annotate_fusion_calls() , should we keep them as generic columns `DomainRetained` , `GeneLoc` and then I can change the name to `kinaseGeneDomainRetained` and `kinaseDomainGeneLoc` specifically for demo file? 

Or we only want to check for kinase domain so keep them hardcoded as `kinaseGeneDomainRetained` and `kinaseDomainGeneLoc` column names?

**Comment by federicomarini** [comment]
As long as
- these are not hard coded in the functions of annoFuse
- they do not belong to the default columns to be found

... I have no problem with either approach

**Comment by kgaonkar6** [comment]
I actually think adding kinaseGeneDomainRetained and kinaseDomainGeneLoc was adding more rows to the fusion calls with status for each Gene1A and Gene1B creating a new row per Fusion (Gene1A--Gene1B). 

So I've added "DomainRetainedInGene1A" ,"DomainRetainedInGene1B" which doesn't add rows .The domain retention code to fusion_driver() function since it seems to be more of a project specific criteria, does that sound ok?

**Comment by jharenza** [comment]
close with #70
